apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-config
  labels:
    app: {{ include "ecommerce.name" . }}
data:
  APP_NAME: {{ .Values.config.APP_NAME | quote }}
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  PORT: {{ .Values.config.PORT | quote }}
