apiVersion: app/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce.fullname" . }}
  labels:
    app: {{ include "ecommerce.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ecommerce.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ecommerce.name" . }}
    spec:
      containers:
        - name: ecommerce
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "ecommerce.fullname" . }}-config
            - secretRef:
                name: {{ include "ecommerce.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
