apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce.fullname" . }}-secret
  labels:
    app: {{ include "ecommerce.name" . }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://ecommerce:change-me@postgres:5432/ecommerce"
